### ISSUE TITLE
Security Disscussion.

### ISSUE THREAD

**Issue by Master-Foo** [Cabal-Syndicate/randora_website#7]
Security is a tricky issue and not easily implemented in a spec. It's more like "I know it when I see it".

So, I'm opening this issue so we can discuss questions and problems.

I'll take a look at everyone's tutorial and give some pointers. The main thing we need to worry about right now is the SECRET_KEY, which is in Django's config file.

Changing this key will screw everyone over. It is what is used to seed encryption algorithms. Thus passwords saved and hashed in the database will no longer be verified if the SECRET_KEY is changed.

In your projects you may want to change it. But don't commit that change. I've put the SECRET_KEY in it's own file so you can configure your git client to ignore the changes. Instructions on how to do that are in the project's README.md

When I host it in production, I will change it to something else.

Anyway, for now, this it the only pressing security issue. When others come up I will step in and point them out.

**Comment by bjdm** [comment]
Can we pull SECRET_KEY from environment variables? This would allow for changes to the production server keys, web servers the devs are using on their own machines and also provide an extra level of obfuscation should the production server ever be compromised.

But as far as security is concerned (I can't speak from experience, I also come from a flask background), does Django not provide tools to help us with this such as safe escaping user input before storing in the db and easy user authentication management?

**Comment by FFX01** [comment]
@mackeybj 

We should be able to store the secret key in env vars, but I'm not sure if that is generally accepted practice or not.

> But as far as security is concerned (I can't speak from experience, I also come from a flask background), does Django not provide tools to help us with this such as safe escaping user input before storing in the db and easy user authentication management?

I'm sure there is a module for that. We should also use regex to make sure no malicious code gets through.

**Comment by bjdm** [comment]
I know that Miguel Grinberg, the guy who wrote the O'Reilly Flask book has suggested the environment variable method before if that's any indication as to whether it is an accepted practice, but I wouldn't be able to say definitively if it's best practice or not.

I was under the impression that the Flask/Django frameworks implemented a sort of parameterized query methodology, but I'm more than happy to work on some regex queries

**Comment by FFX01** [comment]
> I was under the impression that the Flask/Django frameworks implemented a sort of parameterized query methodology, but I'm more than happy to work on some regex queries

No harm in doing both. Regex is pretty simple.

**Comment by Master-Foo** [comment]
@mackeybj Yes, we can pull the SECRET_KEY from ENVVARS and we likely will. But for now we will store it in a flat file. We'll get around to changing that once we have other things in place. Let's get the tutorial behind us first.

@mackeybj Yes, Django safe escapes entries into the DB

@FFX01 Storing the SECRET_KEY in ENVVARS is an accepted practice.

**Comment by Master-Foo** [comment]
@mackeybj and @FFX01 How are you coming along on the tutorial? I don't expect anyone to have finished it, but can we see some progress?

If you don't have much time, maybe just spend 15 - 30 minutes a day to complete one page of the tutorial.

**Comment by bjdm** [comment]
I haven't gotten around to starting yet. I am a few weeks behind with my studies at the moment because of some health problems and my calculus course is kicking my ass at the moment. Should be able to knock over the tutorial sometime in the next week though

**Comment by Master-Foo** [comment]
@mackeybj, don't sacrifice real work for the sake of this project. I'm not putting pressure on you.

We are going to have to move forward at some point though. I may have @FFX01 start the site going and when you do finally finish the tutorial, we'll have some interesting pieces for you to contribute to.

**Comment by FFX01** [comment]
I haven't started the tutorial. I did it a while back, but deleted all the files. I'll go ahead and run through it quickly. It will be a good refresher for me. I currently don't have a job because I'm organizing a move, so I have some extra time.

**Comment by Master-Foo** [comment]
Thanks @FFX01

**Comment by NujabesSoul** [comment]
I'm going to try and work on the tutorial today/tomorrow as well once I get out of work.

**Comment by Master-Foo** [comment]
@NujabesSoul. Cool, let me know when you want me to look at it. Let me know if you have any questions / problems.

**Comment by FFX01** [comment]
OK, update. 

Just finished part 4 of the official django tutorial. Would have gotten more done, but the GF kind of occupied a lot of my time today. I won't have time to work on it tomorrow because I'll be out of town, but I should have some more time on Friday.

Good thing I started going through the tut. Definitely some stuff I forgot in there.

**Comment by Master-Foo** [comment]
Thanks, if you have the time upload your progress into your repositories and I'll look it over.

**Comment by FFX01** [comment]
Update: Finished the unti test section.

[Here's the commit](https://github.com/FFX01/Django-tut)

**Comment by FFX01** [comment]
OK, just finished the complete beginners tutorial. Guess there was only one step left after that last commit. I just pushed the static files to my commit, so it should be a good starting platform at this point. If you want to take a look and suggest some improvements/alterations, that would be great. 

Otherwise, we can probably begin to move forward with laying out the actual website. First thing should probably be the home page. I think we should separate each 'function' of the website(forum, tutorials, etc) into an app module similar to the polls app in my repo linked in my last post. 

@Master-Foo , if you could provide some example sites that you would like to take design cues from, that would be awesome.

**Comment by Master-Foo** [comment]
@FFX01 I'll take a look at it sometime today. I'll make some issues in your repo.

**Comment by Master-Foo** [comment]
@FFX01 I added some issues on your repo.

Let's dedicate some time in the near future to discuss them. There is a lot of ground to cover and it might be best to speak freely in real time. Perhaps over Skype, if not we'll just continue using the issues. But we should dedicate some time to do this when we are both availible for at least an hour.

**Comment by Master-Foo** [comment]
@FFX01 I am free all day today. If you aren't just give me a time.

**Comment by FFX01** [comment]
@Master-Foo Please check out the issue I opened on my repo: [link](https://github.com/FFX01/randora_website/issues/1).

Please also see the latest commits: [link](https://github.com/FFX01/randora_website)

I've implemented a fully functional user module with registration, login, logout, and profile functionality. I still need to embed the correct links and such for navigation(otherwise, you have to manually enter the urls). There will be more functionality added soon and this app will be tied in with the forum module Which I plan to start working on either later this week or next week.

### Planned improvements:
- User avatar image
- User bio
- User links

**Comment by Master-Foo** [comment]
@FFX01 I'll take a look at it later today.

Hold off on the planned improvements. We have more important things to implement right now. We'll get around to bells and whistles after we have the main modules in place.
